mock SetAccountStorageHook ( 1809217465971809 , 123 ) ukmNoResult();
mock GetAccountStorageHook ( 1809217465971809 ) ukmInt64Result(123);

call :: bytes_hooks :: empty;
return_value_to_arg;
push "setMyData(Uint64)";
call :: bytes_hooks :: append_str;
return_value_to_arg;
push 123_u64;
call :: bytes_hooks :: append_u64;
return_value;
mock CallData;

call_contract 12345;
return_value;
check_eq ();

push_status;
check_eq 2;


call :: bytes_hooks :: empty;
return_value_to_arg;
push "getMyData()";
call :: bytes_hooks :: append_str;
return_value;
mock CallData;

call_contract 12345;
return_value;
check_eq ();

push_status;
check_eq 2;

output_to_arg;
call :: test_helpers :: decode_single_u64;
return_value;

check_eq 123_u64

