mock SetAccountStorageHook ( 89307555350153532481150451243271458944170707741354029868021544305102042370102 , 123 ) ulmNoResult();
mock GetAccountStorageHook ( 89307555350153532481150451243271458944170707741354029868021544305102042370102 ) ulmIntResult(123, u256);

push "setMyDataKey";
hold_string_from_test_stack;
push "uint64";
push "uint64";
hold_list_values_from_test_stack;
push 555_u64;
push 123_u64;
hold_list_values_from_test_stack;
encode_call_data;
return_value;
mock CallData;

call_contract 12345;
return_value;
check_eq ();

push_status;
check_eq 2;


push "getMyDataKey";
hold_string_from_test_stack;
push "uint64";
hold_list_values_from_test_stack;
push 555_u64;
hold_list_values_from_test_stack;
encode_call_data;
return_value;
mock CallData;

call_contract 12345;
return_value;
check_eq ();

push_status;
check_eq 2;

output_to_arg;
call :: test_helpers :: decode_single_u64;
return_value;

check_eq 123_u64

