mock SetAccountStorageHook ( 1809217465971809 , 123 ) ulmNoResult();
mock GetAccountStorageHook ( 1809217465971809 ) ulmIntResult(123, u64);

push "setMyData";
hold_string_from_test_stack; 
push "uint64";
hold_list_values_from_test_stack;
push 123_u64;
hold_list_values_from_test_stack; 
encode_call_data; 
return_value;
mock CallData;

call_contract 12345;
return_value;
check_eq ();

push_status;
check_eq 2;


push "getMyData";
hold_string_from_test_stack; 
encode_call_data; 
return_value;
mock CallData;

call_contract 12345;
return_value;
check_eq ();

push_status;
check_eq 2;

output_to_arg;
call :: test_helpers :: decode_single_u64;
return_value;

check_eq 123_u64

