mock SetAccountStorageHook ( storageKey("myDataKey", 555_u64:u64) , 123_u64 ) ulmNoResult();
mock GetAccountStorageHook ( storageKey("myDataKey", 555_u64:u64) ) ulmIntResult(123, u256);

encode_call_data setMyDataKey(555_u64:u64, 123_u64:u64);
return_value;
mock CallData;

call_contract 12345;
return_value;
check_eq ();

push_status;
check_eq 2;


encode_call_data getMyDataKey(555_u64:u64);
return_value;
mock CallData;

call_contract 12345;
return_value;
check_eq ();

push_status;
check_eq 2;

output_to_arg;
call :: test_helpers :: decode_single_u64;
return_value;

check_eq 123_u64

